import type { Metadata } from "next";
import {Montserrat} from "next/font/google";
import 'modern-normalize';
import "./globals.css";

import { Providers } from "./provider";

const geistMont = Montserrat({
  variable: "--font-main",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistMont.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
